import "~/styles/globals.css";
import "@uploadthing/react/styles.css";

import { GeistSans } from "geist/font/sans";
import { ThemeProvider } from "next-themes";
import { ClerkProvider } from "@clerk/nextjs";
import TopNav from "./_components/TopNav";

export const metadata = {
  title: "T3 Gallery App",
  description: "Generated by marcomania",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {  
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en" className={`${GeistSans.variable} flex flex-col gap-4`}>
        <body>
          <ThemeProvider attribute="class" themes={["dark"]}>
            <TopNav/>
            {children}
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
