import "~/styles/globals.css";
import "@uploadthing/react/styles.css";

import { GeistSans } from "geist/font/sans";
import { ThemeProvider } from "next-themes";
import { ClerkProvider } from "@clerk/nextjs";
import TopNav from "./_components/TopNav";
import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
import { extractRouterConfig } from "uploadthing/server";
import { ourFileRouter } from "./api/uploadthing/core";
import { Toaster } from "~/components/ui/sonner";
import { CSPostHogProvider } from "./_analytics/providers";

export const metadata = {
  title: "T3 Gallery App",
  description: "Generated by marcomania",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  modal,
  children,
}: {  
  modal: React.ReactNode;
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en" className={`${GeistSans.variable}`}>
        <CSPostHogProvider>
          <NextSSRPlugin routerConfig={extractRouterConfig(ourFileRouter)}/>
          <body>
            <ThemeProvider attribute="class" defaultTheme="dark">
              <div className="h-screen grid grid-rows-[auto,1fr]">
                <TopNav/>
                <main className="overflow-y-scroll" >
                  {children}
                </main>
              </div>
              {modal}
              <div id="modal-root" />
              <Toaster/>
            </ThemeProvider>
          </body>
        </CSPostHogProvider>
      </html>
    </ClerkProvider>
  );
}
